enum SumChetvelDanType {
  lei,
  hralh,
  lakluh,
  pekchhuah,
  debtRepaymentByDebtor,
  debtRepaymentToCreditor,
  bankToCash,
  cashToBank,
  purchaseReturn,
  saleReturn,
  capitalInjection,
  openingBalanceCash,
  openingBalanceBank,
}
